#!/usr/bin/env bash

mkdir -p out

if [[ "$OSTYPE" == "darwin"* ]]; then

    g++ -fPIC src/*.cc -Wall -O0 \
    -I include \
    -I lib/gl3w/include \
    lib/gl3w/src/gl3w.c \
    -I lib/glfw/include \
    -L lib/glfw/src \
    -lglfw \
    -framework OpenGL \
    -lpthread -ldl -lm \
    -shared -o out/libburner.so
else

    g++ -fPIC src/*.cc -Wall -O0 \
    -I include \
    -I lib/gl3w/include \
    lib/gl3w/src/gl3w.c \
    -I lib/glfw/include \
    -L lib/glfw/src \
    -lglfw3 \
    -lGL \
    -lX11 \
    -lpthread -ldl -lm \
    -shared -o out/libburner.so
fi
