#!/usr/bin/env bash

# run from anywhere
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

cd $DIR

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/out

echo "#define LIB_VERSION 0" >| "out/version.h";

if g++ -fPIC examples/simple.cc -DDEVELOPMENT_MODE -DGAME_CODE -Wall -O0 \
-I include \
-L out -lburner \
-shared -o out/libjam.so
then out/burner; fi
